### PR TITLE
fixed compile error against v1.0.0

### PR DESCRIPTION
**Pull request by millergarym**
#1

### CODE REVIEW

**Comment by jpillora** [comment]
Thanks! Working on the completion wrapper now

**Comment by jpillora** [comment]
Currently have:

Opts code

```go
//Completer represents a shell-completion
//implementation for a single field.
type Completer interface {
	//Complete provides the users input and should
	//return a corresponding set of valid inputs
	Complete(user string) []string
}
```

User code

```go
type custom string

var valid = []string{"a", "b", "c"}

func (c custom) Complete(s string) []string {
	return valid
}

func (c *custom) Set(s string) error {
	for _, v := range valid {
		if s == v {
			*c = custom(s)
			return nil
		}
	}
	return fmt.Errorf("must be one of: %v", strings.Join(valid, ", "))
}
```

**Comment by jpillora** [comment]
Thoughts?

**Comment by millergarym** [comment]
I don't have enough experience with completer to really comment.
Posener's has info about the location in the completion which I can see being useful.


github.com/posener/complete@v1.2.1/predict.go
https://github.com/posener/complete/blob/master/predict.go
``` go
type Predictor interface {
	Predict(Args) []string
}
```
github.com/posener/complete@v1.2.1/args.go 
https://github.com/posener/complete/blob/master/args.go
``` go
// Args describes command line arguments
type Args struct {
	// All lists of all arguments in command line (not including the command itself)
	All []string
	// Completed lists of all completed arguments in command line,
	// If the last one is still being typed - no space after it,
	// it won't appear in this list of arguments.
	Completed []string
	// Last argument in command line, the one being typed, if the last
	// character in the command line is a space, this argument will be empty,
	// otherwise this would be the last word.
	Last string
	// LastCompleted is the last argument that was fully typed.
	// If the last character in the command line is space, this would be the
	// last word, otherwise, it would be the word before that.
	LastCompleted string
}
```

**Comment by jpillora** [comment]
Yeah I had a look at those types, I don't think you can get cursor info from `Args`. Also, was wondering when you'd need anything other than `Last`? For future version, we could always include another interface `CompleterContext` which included a context object with more information.

**Pull request merged**
